#!/usr/bin/env bash
# Generate a Homebrew formula (prebuilt-binary) for the marrow CLI from the
# release artifacts' checksums. Emits the formula to stdout.
#
# Usage: gen-homebrew-formula.sh <version> <artifacts-dir> [owner/repo]
#   <artifacts-dir> must contain SHA256SUMS (one line per `marrow-<target>.*`).
set -euo pipefail

VERSION="${1:?version required}"
DIR="${2:?artifacts dir required}"
REPO="${3:-Besendorfer/marrow}"
TAG="cli-v${VERSION}"
BASE="https://github.com/${REPO}/releases/download/${TAG}"

# Look up the sha256 for an artifact filename in SHA256SUMS.
sha() {
  local file="$1" line
  line=$(grep -E " [ *]${file}\$" "${DIR}/SHA256SUMS" || true)
  if [ -z "${line}" ]; then
    echo "error: no checksum for ${file} in ${DIR}/SHA256SUMS" >&2
    exit 1
  fi
  echo "${line%% *}"
}

ARM_MAC="$(sha "marrow-aarch64-apple-darwin.tar.gz")"
X86_MAC="$(sha "marrow-x86_64-apple-darwin.tar.gz")"
X86_LINUX="$(sha "marrow-x86_64-unknown-linux-gnu.tar.gz")"

cat <<EOF
# Generated by .github/scripts/gen-homebrew-formula.sh — do not edit by hand.
class Marrow < Formula
  desc "Surface the parts of a GitHub PR that matter — an AI PR review TUI"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE}/marrow-aarch64-apple-darwin.tar.gz"
      sha256 "${ARM_MAC}"
    else
      url "${BASE}/marrow-x86_64-apple-darwin.tar.gz"
      sha256 "${X86_MAC}"
    end
  end

  on_linux do
    url "${BASE}/marrow-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "${X86_LINUX}"
  end

  def install
    bin.install "marrow"
  end

  test do
    assert_match "marrow", shell_output("#{bin}/marrow --help 2>&1")
  end
end
EOF
